import type { Metadata } from "next";
//metadata는 서버 컴포넌트에서만 사용할 수 있습니다. 따라서 use client가 선언된 파일에서 metadata를 함께 사용할 수 없습니다.
//클라이언트 컴포넌트에서 필요한 로직(예: SessionProvider)은 별도의 컴포넌트로 분리하여 처리합니다.

//import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
